### ISSUE TITLE
[META] v1.0.0 For .NET Core Sdk 1.0 RTM

### ISSUE THREAD

**Issue by enricosada** [dotnet/netcorecli-fsc#72]
as per [Roadmap](https://github.com/dotnet/netcorecli-fsc/wiki/Roadmap)

tracked status in [Project - Works in .NET Core Sdk 1.0 RTM](https://github.com/dotnet/netcorecli-fsc/projects/2)

For .NET Core Sdk RTM (or RTW)

- [x] 1. Create `FSharp.Core` and  `FSharp.Compiler.Tools` 4.1.0-rc1 packages on dev feed
- [x] 2. use `FscTask` instead of `dotnet-compile-fsc` ( PR #61 )
- [x] 3. `FSharp.Core` 4.1.0-rc1 package on nuget.org
- [x] 4. `FSharp.Compiler.Tools` 4.1.0-rc1 package on nuget.org
- [x] 5. `FSharp.Sdk` and `FSharp.NET.Sdk` 1.0.0 on nuget.org
- [x] 6. update templates in `dotnet/templating` ( PR https://github.com/dotnet/templating )
    require 2, 3, 4
- [x] 7. templates merged in `dotnet/cli` ~~using `FSharp.Sdk`~~

Not related to sdk directly

- [x] fix FSAC (vscode,ionide,vim,emac) intellisense
- [x] check build `net451` on osx

/cc @dsyme @cartermp

**Comment by enricosada** [comment]
closing.

`dotnet new` -> `dotnet restore` -> intellisense FSAC~ -> F5 -> (build, run) -> debug!

![recf-ionide2](https://cloud.githubusercontent.com/assets/147243/24086053/528e2114-0d08-11e7-9408-411337675b40.gif)
